# -*- coding: utf-8 -*-
"""Water Quality Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AytMi22poV7B8Paf1pgCgRPONDe22mq-
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

"""# Load Dataset"""

df = pd.read_csv("/content/sample_data/archive (9).zip")

print("Dataset Loaded Successfully")
print(df.head())

"""# Display Dataset Information"""

print(df.info())
print(df.describe())

"""# Check Missing Values"""

print(df.isnull().sum())

"""# Separate Features and Target"""

X = df.drop("Potability", axis=1)
y = df["Potability"]

"""# Handle Missing Values"""

imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

"""# Split Dataset into Training and Testing Data"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""# Train Machine Learning Model"""

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
model.fit(X_train, y_train)
print("Model Training Completed")

"""# Predict Test Data"""

y_pred = model.predict(X_test)

"""# Calculate Accuracy"""

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", round(accuracy * 100, 2), "%")

"""# User Input Sample Data"""

sample_data = [[
    7.5,
    200,
    18000,
    7.0,
    300,
    450,
    12,
    70,
    4.0
]]

"""# Predict Water Quality"""

result = model.predict(sample_data)

"""# Display Result"""

if result[0] == 1:
    print("Water is Safe for Drinking")
else:
    print("Water is Not Safe for Drinking")